#!/usr/bin/env python3

"""
Author: Juan Jiménez, flybd5@gmail.com
Copyright 2020 by Juan Jiménez
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

import json
import random
import time
from urllib.request import urlopen

recordstocreate = 100000
localfilename = 'seed_dataset'
outfile = open(localfilename, 'w')

outfile.write('type: f\ncount: ',str(recordstocreate),'\nnumbits: 256\n')
for x in range(0,recordstocreate):
  resp = urlopen(f'https://api.helioviewer.org/?action=getRandomSeed')
  if resp.getcode() != 200:
    print('Unable to connect to Helioviewer API.')
    break;
  else:
    resp_dict = json.load(resp)
    seed = resp_dict['seed']
    if seed is None:
      print('Seed not received.')
      break;
    else:
      res = ''.join(bin(int(i,16))[2:].zfill(4) for i in seed)
      outfile.write(str(res)+'\n')
  print(x,' ',seed,' ',len(str(res)))
  time.sleep(0.02)

outfile.close
